Raise required compiler to Rust 1.70
Required by latest version of once_cell.

    error: package `once_cell v1.21.0` cannot be built because it
    requires rustc 1.70 or newer, while the currently active rustc
    version is 1.62.1