Raise minimum tested compiler to rust 1.73
Required by postcard's dependency on cobs.

    error[E0658]: use of unstable library feature 'int_roundings'
      --> $CARGO_HOME/registry/src/index.crates.io-6f17d22bba15001f/cobs-0.3.0/src/lib.rs:46:16
       |
    46 |     source_len.div_ceil(254)
       |                ^^^^^^^^